# Site settings
title: WzBozz Blog
email: zbwang86@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  WzBozz'z Blog 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wzbozz.github.io" # the base hostname & protocol for your site
twitter_username: wzbozz
github_username:  wzbozz
linkedin_url: "" 
facebook_url: ""
flickr_url: ""
disqus_shortname: wzbozzgithubio

imageurl: "/images"
#imageurl: "https://wzbozz.github.io/images"

# Build settings
markdown: kramdown
kramdown:
        input: GFM
        hard_wrap: true
        syntax_highlighter_opts:
                disable: true
# _pages
include: ['_pages']
